# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Base Ecommerce',
    'version': '1.0',
    'summary': 'Base Ecommerce',
    'sequence': 10,
    'description': """Base Ecommerce""",
    'category': '',
    'website': 'https://www.odoo.com/app/',
    'depends': ["base", "mail", "stock", "sale", "l10n_in_sale", "account"],
    'data': [
        'security/ir.model.access.csv',
        'security/shop_instance_security.xml',
        'data/cron_order.xml',
        'data/decimal_precision_data.xml',
        'views/menu.xml',
        'views/sales_channel_view.xml',
        'views/shop_instance_view.xml',
        'views/shop_import_logs.xml',
        'views/inherit_sale_order.xml',
        'views/inherit_product_template_view.xml',
        'views/exception_order_view.xml',
        'views/inherit_product_category.xml',
        'views/seller_master_view.xml',
        'views/inherit_account_journal.xml',
        'views/modified_account_move.xml',
        'report/invoice_report.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
