from . import shop_instance
from . import sales_channel
from . import shop_import_logs
from . import inherit_sale_order
from . import inherit_product_template
from . import inherit_product_category
from . import seller_master
from . import inherit_account_journal
from . import inherit_account_move
